# Spring Boot application configuration
server:
  # HTTP port the embedded Tomcat listens on
  port: 8080

spring:
  datasource:
    # For local development we use in-memory H2. Switch to MySQL/PostgreSQL in production.
    url: jdbc:h2:mem:wetalk;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      # Auto create/update schema in dev. Prefer Flyway for managed migrations.
      ddl-auto: update
    # Log SQL for debugging
    show-sql: true
  h2:
    console:
      # Enable H2 web console for quick inspection at /h2-console
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework: INFO
    com.wetalk: DEBUG